<?php

/**
 * This file was automatically generated by Fusion.
 * You should not edit it.
 */
namespace Fusion\Generated\Pages;

use App\Models\Podcast;
class DynamicPodcastGenerated extends \Fusion\FusionPage
{
    #[\Fusion\Attributes\ServerOnly]
    public array $discoveredProps = ['slug', 'podcastsRaw'];
    use \Fusion\Concerns\IsProceduralPage;
    public function runProceduralCode()
    {
        $slug = $this->prop(name: 'slug')->fromRoute('podcast')->value();
        $podcastsRaw = $this->prop(name: 'podcastsRaw', default: fn() => Podcast::all())->value();
        $this->syncProps(get_defined_vars());
    }
}