/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutTemplate: typeof import('./resources/js/Components/AboutTemplate.vue')['default']
    AppLayout: typeof import('./resources/js/Layouts/AppLayout.vue')['default']
    BaseButton: typeof import('./resources/js/Components/BaseButton.vue')['default']
    BaseIcon: typeof import('./resources/js/Components/BaseIcon.vue')['default']
    DarkModeSwitch: typeof import('./resources/js/Components/DarkModeSwitch.vue')['default']
    HeroSection: typeof import('./resources/js/Components/HeroSection.vue')['default']
    LoadingIcon: typeof import('./resources/js/Components/LoadingIcon.vue')['default']
    NavBar: typeof import('./resources/js/Components/NavBar.vue')['default']
    NavHamburger: typeof import('./resources/js/Components/NavHamburger.vue')['default']
    NavPrimary: typeof import('./resources/js/Components/NavPrimary.vue')['default']
    NavSecondary: typeof import('./resources/js/Components/NavSecondary.vue')['default']
    PageHome: typeof import('./resources/js/Components/PageHome.vue')['default']
    Podcast: typeof import('./resources/js/Components/Podcast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscribeSection: typeof import('./resources/js/Components/SubscribeSection.vue')['default']
    TheFooter: typeof import('./resources/js/Components/TheFooter.vue')['default']
    TheHeader: typeof import('./resources/js/Components/TheHeader.vue')['default']
    TheLogo: typeof import('./resources/js/Components/TheLogo.vue')['default']
    ThePost: typeof import('./resources/js/Components/ThePost.vue')['default']
    WalkThrough: typeof import('./resources/js/Components/WalkThrough.vue')['default']
  }
}
